// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doss.proto

package doss.net;

public final class DossProtocol {
  private DossProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage {
    // Use Request.newBuilder() to construct.
    private Request() {
      initFields();
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return doss.net.DossProtocol.internal_static_doss_net_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return doss.net.DossProtocol.internal_static_doss_net_Request_fieldAccessorTable;
    }
    
    // optional .doss.net.StatRequest statRequest = 2;
    public static final int STATREQUEST_FIELD_NUMBER = 2;
    private boolean hasStatRequest;
    private doss.net.DossProtocol.StatRequest statRequest_;
    public boolean hasStatRequest() { return hasStatRequest; }
    public doss.net.DossProtocol.StatRequest getStatRequest() { return statRequest_; }
    
    private void initFields() {
      statRequest_ = doss.net.DossProtocol.StatRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasStatRequest()) {
        if (!getStatRequest().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStatRequest()) {
        output.writeMessage(2, getStatRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStatRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStatRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static doss.net.DossProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(doss.net.DossProtocol.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private doss.net.DossProtocol.Request result;
      
      // Construct using doss.net.DossProtocol.Request.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new doss.net.DossProtocol.Request();
        return builder;
      }
      
      protected doss.net.DossProtocol.Request internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new doss.net.DossProtocol.Request();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return doss.net.DossProtocol.Request.getDescriptor();
      }
      
      public doss.net.DossProtocol.Request getDefaultInstanceForType() {
        return doss.net.DossProtocol.Request.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public doss.net.DossProtocol.Request build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private doss.net.DossProtocol.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public doss.net.DossProtocol.Request buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        doss.net.DossProtocol.Request returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof doss.net.DossProtocol.Request) {
          return mergeFrom((doss.net.DossProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(doss.net.DossProtocol.Request other) {
        if (other == doss.net.DossProtocol.Request.getDefaultInstance()) return this;
        if (other.hasStatRequest()) {
          mergeStatRequest(other.getStatRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 18: {
              doss.net.DossProtocol.StatRequest.Builder subBuilder = doss.net.DossProtocol.StatRequest.newBuilder();
              if (hasStatRequest()) {
                subBuilder.mergeFrom(getStatRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStatRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .doss.net.StatRequest statRequest = 2;
      public boolean hasStatRequest() {
        return result.hasStatRequest();
      }
      public doss.net.DossProtocol.StatRequest getStatRequest() {
        return result.getStatRequest();
      }
      public Builder setStatRequest(doss.net.DossProtocol.StatRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStatRequest = true;
        result.statRequest_ = value;
        return this;
      }
      public Builder setStatRequest(doss.net.DossProtocol.StatRequest.Builder builderForValue) {
        result.hasStatRequest = true;
        result.statRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeStatRequest(doss.net.DossProtocol.StatRequest value) {
        if (result.hasStatRequest() &&
            result.statRequest_ != doss.net.DossProtocol.StatRequest.getDefaultInstance()) {
          result.statRequest_ =
            doss.net.DossProtocol.StatRequest.newBuilder(result.statRequest_).mergeFrom(value).buildPartial();
        } else {
          result.statRequest_ = value;
        }
        result.hasStatRequest = true;
        return this;
      }
      public Builder clearStatRequest() {
        result.hasStatRequest = false;
        result.statRequest_ = doss.net.DossProtocol.StatRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:doss.net.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      doss.net.DossProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:doss.net.Request)
  }
  
  public static final class StatRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use StatRequest.newBuilder() to construct.
    private StatRequest() {
      initFields();
    }
    private StatRequest(boolean noInit) {}
    
    private static final StatRequest defaultInstance;
    public static StatRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return doss.net.DossProtocol.internal_static_doss_net_StatRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return doss.net.DossProtocol.internal_static_doss_net_StatRequest_fieldAccessorTable;
    }
    
    // required int64 blobId = 1;
    public static final int BLOBID_FIELD_NUMBER = 1;
    private boolean hasBlobId;
    private long blobId_ = 0L;
    public boolean hasBlobId() { return hasBlobId; }
    public long getBlobId() { return blobId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasBlobId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasBlobId()) {
        output.writeInt64(1, getBlobId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasBlobId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getBlobId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static doss.net.DossProtocol.StatRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.StatRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.StatRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(doss.net.DossProtocol.StatRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private doss.net.DossProtocol.StatRequest result;
      
      // Construct using doss.net.DossProtocol.StatRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new doss.net.DossProtocol.StatRequest();
        return builder;
      }
      
      protected doss.net.DossProtocol.StatRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new doss.net.DossProtocol.StatRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return doss.net.DossProtocol.StatRequest.getDescriptor();
      }
      
      public doss.net.DossProtocol.StatRequest getDefaultInstanceForType() {
        return doss.net.DossProtocol.StatRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public doss.net.DossProtocol.StatRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private doss.net.DossProtocol.StatRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public doss.net.DossProtocol.StatRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        doss.net.DossProtocol.StatRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof doss.net.DossProtocol.StatRequest) {
          return mergeFrom((doss.net.DossProtocol.StatRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(doss.net.DossProtocol.StatRequest other) {
        if (other == doss.net.DossProtocol.StatRequest.getDefaultInstance()) return this;
        if (other.hasBlobId()) {
          setBlobId(other.getBlobId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setBlobId(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 blobId = 1;
      public boolean hasBlobId() {
        return result.hasBlobId();
      }
      public long getBlobId() {
        return result.getBlobId();
      }
      public Builder setBlobId(long value) {
        result.hasBlobId = true;
        result.blobId_ = value;
        return this;
      }
      public Builder clearBlobId() {
        result.hasBlobId = false;
        result.blobId_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:doss.net.StatRequest)
    }
    
    static {
      defaultInstance = new StatRequest(true);
      doss.net.DossProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:doss.net.StatRequest)
  }
  
  public static final class Response extends
      com.google.protobuf.GeneratedMessage {
    // Use Response.newBuilder() to construct.
    private Response() {
      initFields();
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return doss.net.DossProtocol.internal_static_doss_net_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return doss.net.DossProtocol.internal_static_doss_net_Response_fieldAccessorTable;
    }
    
    // optional .doss.net.StatResponse statResponse = 2;
    public static final int STATRESPONSE_FIELD_NUMBER = 2;
    private boolean hasStatResponse;
    private doss.net.DossProtocol.StatResponse statResponse_;
    public boolean hasStatResponse() { return hasStatResponse; }
    public doss.net.DossProtocol.StatResponse getStatResponse() { return statResponse_; }
    
    // optional .doss.net.NoSuchBlobResponse noSuchBlobResponse = 16;
    public static final int NOSUCHBLOBRESPONSE_FIELD_NUMBER = 16;
    private boolean hasNoSuchBlobResponse;
    private doss.net.DossProtocol.NoSuchBlobResponse noSuchBlobResponse_;
    public boolean hasNoSuchBlobResponse() { return hasNoSuchBlobResponse; }
    public doss.net.DossProtocol.NoSuchBlobResponse getNoSuchBlobResponse() { return noSuchBlobResponse_; }
    
    private void initFields() {
      statResponse_ = doss.net.DossProtocol.StatResponse.getDefaultInstance();
      noSuchBlobResponse_ = doss.net.DossProtocol.NoSuchBlobResponse.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasStatResponse()) {
        if (!getStatResponse().isInitialized()) return false;
      }
      if (hasNoSuchBlobResponse()) {
        if (!getNoSuchBlobResponse().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStatResponse()) {
        output.writeMessage(2, getStatResponse());
      }
      if (hasNoSuchBlobResponse()) {
        output.writeMessage(16, getNoSuchBlobResponse());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStatResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStatResponse());
      }
      if (hasNoSuchBlobResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getNoSuchBlobResponse());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static doss.net.DossProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(doss.net.DossProtocol.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private doss.net.DossProtocol.Response result;
      
      // Construct using doss.net.DossProtocol.Response.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new doss.net.DossProtocol.Response();
        return builder;
      }
      
      protected doss.net.DossProtocol.Response internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new doss.net.DossProtocol.Response();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return doss.net.DossProtocol.Response.getDescriptor();
      }
      
      public doss.net.DossProtocol.Response getDefaultInstanceForType() {
        return doss.net.DossProtocol.Response.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public doss.net.DossProtocol.Response build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private doss.net.DossProtocol.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public doss.net.DossProtocol.Response buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        doss.net.DossProtocol.Response returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof doss.net.DossProtocol.Response) {
          return mergeFrom((doss.net.DossProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(doss.net.DossProtocol.Response other) {
        if (other == doss.net.DossProtocol.Response.getDefaultInstance()) return this;
        if (other.hasStatResponse()) {
          mergeStatResponse(other.getStatResponse());
        }
        if (other.hasNoSuchBlobResponse()) {
          mergeNoSuchBlobResponse(other.getNoSuchBlobResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 18: {
              doss.net.DossProtocol.StatResponse.Builder subBuilder = doss.net.DossProtocol.StatResponse.newBuilder();
              if (hasStatResponse()) {
                subBuilder.mergeFrom(getStatResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStatResponse(subBuilder.buildPartial());
              break;
            }
            case 130: {
              doss.net.DossProtocol.NoSuchBlobResponse.Builder subBuilder = doss.net.DossProtocol.NoSuchBlobResponse.newBuilder();
              if (hasNoSuchBlobResponse()) {
                subBuilder.mergeFrom(getNoSuchBlobResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNoSuchBlobResponse(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .doss.net.StatResponse statResponse = 2;
      public boolean hasStatResponse() {
        return result.hasStatResponse();
      }
      public doss.net.DossProtocol.StatResponse getStatResponse() {
        return result.getStatResponse();
      }
      public Builder setStatResponse(doss.net.DossProtocol.StatResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStatResponse = true;
        result.statResponse_ = value;
        return this;
      }
      public Builder setStatResponse(doss.net.DossProtocol.StatResponse.Builder builderForValue) {
        result.hasStatResponse = true;
        result.statResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeStatResponse(doss.net.DossProtocol.StatResponse value) {
        if (result.hasStatResponse() &&
            result.statResponse_ != doss.net.DossProtocol.StatResponse.getDefaultInstance()) {
          result.statResponse_ =
            doss.net.DossProtocol.StatResponse.newBuilder(result.statResponse_).mergeFrom(value).buildPartial();
        } else {
          result.statResponse_ = value;
        }
        result.hasStatResponse = true;
        return this;
      }
      public Builder clearStatResponse() {
        result.hasStatResponse = false;
        result.statResponse_ = doss.net.DossProtocol.StatResponse.getDefaultInstance();
        return this;
      }
      
      // optional .doss.net.NoSuchBlobResponse noSuchBlobResponse = 16;
      public boolean hasNoSuchBlobResponse() {
        return result.hasNoSuchBlobResponse();
      }
      public doss.net.DossProtocol.NoSuchBlobResponse getNoSuchBlobResponse() {
        return result.getNoSuchBlobResponse();
      }
      public Builder setNoSuchBlobResponse(doss.net.DossProtocol.NoSuchBlobResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNoSuchBlobResponse = true;
        result.noSuchBlobResponse_ = value;
        return this;
      }
      public Builder setNoSuchBlobResponse(doss.net.DossProtocol.NoSuchBlobResponse.Builder builderForValue) {
        result.hasNoSuchBlobResponse = true;
        result.noSuchBlobResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeNoSuchBlobResponse(doss.net.DossProtocol.NoSuchBlobResponse value) {
        if (result.hasNoSuchBlobResponse() &&
            result.noSuchBlobResponse_ != doss.net.DossProtocol.NoSuchBlobResponse.getDefaultInstance()) {
          result.noSuchBlobResponse_ =
            doss.net.DossProtocol.NoSuchBlobResponse.newBuilder(result.noSuchBlobResponse_).mergeFrom(value).buildPartial();
        } else {
          result.noSuchBlobResponse_ = value;
        }
        result.hasNoSuchBlobResponse = true;
        return this;
      }
      public Builder clearNoSuchBlobResponse() {
        result.hasNoSuchBlobResponse = false;
        result.noSuchBlobResponse_ = doss.net.DossProtocol.NoSuchBlobResponse.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:doss.net.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      doss.net.DossProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:doss.net.Response)
  }
  
  public static final class StatResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use StatResponse.newBuilder() to construct.
    private StatResponse() {
      initFields();
    }
    private StatResponse(boolean noInit) {}
    
    private static final StatResponse defaultInstance;
    public static StatResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return doss.net.DossProtocol.internal_static_doss_net_StatResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return doss.net.DossProtocol.internal_static_doss_net_StatResponse_fieldAccessorTable;
    }
    
    // required int64 blobId = 1;
    public static final int BLOBID_FIELD_NUMBER = 1;
    private boolean hasBlobId;
    private long blobId_ = 0L;
    public boolean hasBlobId() { return hasBlobId; }
    public long getBlobId() { return blobId_; }
    
    // required int64 size = 2;
    public static final int SIZE_FIELD_NUMBER = 2;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasBlobId) return false;
      if (!hasSize) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasBlobId()) {
        output.writeInt64(1, getBlobId());
      }
      if (hasSize()) {
        output.writeInt64(2, getSize());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasBlobId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getBlobId());
      }
      if (hasSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getSize());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static doss.net.DossProtocol.StatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.StatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.StatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(doss.net.DossProtocol.StatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private doss.net.DossProtocol.StatResponse result;
      
      // Construct using doss.net.DossProtocol.StatResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new doss.net.DossProtocol.StatResponse();
        return builder;
      }
      
      protected doss.net.DossProtocol.StatResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new doss.net.DossProtocol.StatResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return doss.net.DossProtocol.StatResponse.getDescriptor();
      }
      
      public doss.net.DossProtocol.StatResponse getDefaultInstanceForType() {
        return doss.net.DossProtocol.StatResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public doss.net.DossProtocol.StatResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private doss.net.DossProtocol.StatResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public doss.net.DossProtocol.StatResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        doss.net.DossProtocol.StatResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof doss.net.DossProtocol.StatResponse) {
          return mergeFrom((doss.net.DossProtocol.StatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(doss.net.DossProtocol.StatResponse other) {
        if (other == doss.net.DossProtocol.StatResponse.getDefaultInstance()) return this;
        if (other.hasBlobId()) {
          setBlobId(other.getBlobId());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setBlobId(input.readInt64());
              break;
            }
            case 16: {
              setSize(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 blobId = 1;
      public boolean hasBlobId() {
        return result.hasBlobId();
      }
      public long getBlobId() {
        return result.getBlobId();
      }
      public Builder setBlobId(long value) {
        result.hasBlobId = true;
        result.blobId_ = value;
        return this;
      }
      public Builder clearBlobId() {
        result.hasBlobId = false;
        result.blobId_ = 0L;
        return this;
      }
      
      // required int64 size = 2;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:doss.net.StatResponse)
    }
    
    static {
      defaultInstance = new StatResponse(true);
      doss.net.DossProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:doss.net.StatResponse)
  }
  
  public static final class NoSuchBlobResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use NoSuchBlobResponse.newBuilder() to construct.
    private NoSuchBlobResponse() {
      initFields();
    }
    private NoSuchBlobResponse(boolean noInit) {}
    
    private static final NoSuchBlobResponse defaultInstance;
    public static NoSuchBlobResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public NoSuchBlobResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return doss.net.DossProtocol.internal_static_doss_net_NoSuchBlobResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return doss.net.DossProtocol.internal_static_doss_net_NoSuchBlobResponse_fieldAccessorTable;
    }
    
    // required int64 blobId = 1;
    public static final int BLOBID_FIELD_NUMBER = 1;
    private boolean hasBlobId;
    private long blobId_ = 0L;
    public boolean hasBlobId() { return hasBlobId; }
    public long getBlobId() { return blobId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasBlobId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasBlobId()) {
        output.writeInt64(1, getBlobId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasBlobId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getBlobId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static doss.net.DossProtocol.NoSuchBlobResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(doss.net.DossProtocol.NoSuchBlobResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private doss.net.DossProtocol.NoSuchBlobResponse result;
      
      // Construct using doss.net.DossProtocol.NoSuchBlobResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new doss.net.DossProtocol.NoSuchBlobResponse();
        return builder;
      }
      
      protected doss.net.DossProtocol.NoSuchBlobResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new doss.net.DossProtocol.NoSuchBlobResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return doss.net.DossProtocol.NoSuchBlobResponse.getDescriptor();
      }
      
      public doss.net.DossProtocol.NoSuchBlobResponse getDefaultInstanceForType() {
        return doss.net.DossProtocol.NoSuchBlobResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public doss.net.DossProtocol.NoSuchBlobResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private doss.net.DossProtocol.NoSuchBlobResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public doss.net.DossProtocol.NoSuchBlobResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        doss.net.DossProtocol.NoSuchBlobResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof doss.net.DossProtocol.NoSuchBlobResponse) {
          return mergeFrom((doss.net.DossProtocol.NoSuchBlobResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(doss.net.DossProtocol.NoSuchBlobResponse other) {
        if (other == doss.net.DossProtocol.NoSuchBlobResponse.getDefaultInstance()) return this;
        if (other.hasBlobId()) {
          setBlobId(other.getBlobId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setBlobId(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 blobId = 1;
      public boolean hasBlobId() {
        return result.hasBlobId();
      }
      public long getBlobId() {
        return result.getBlobId();
      }
      public Builder setBlobId(long value) {
        result.hasBlobId = true;
        result.blobId_ = value;
        return this;
      }
      public Builder clearBlobId() {
        result.hasBlobId = false;
        result.blobId_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:doss.net.NoSuchBlobResponse)
    }
    
    static {
      defaultInstance = new NoSuchBlobResponse(true);
      doss.net.DossProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:doss.net.NoSuchBlobResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doss_net_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doss_net_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doss_net_StatRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doss_net_StatRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doss_net_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doss_net_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doss_net_StatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doss_net_StatResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_doss_net_NoSuchBlobResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_doss_net_NoSuchBlobResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndoss.proto\022\010doss.net\"5\n\007Request\022*\n\013sta" +
      "tRequest\030\002 \001(\0132\025.doss.net.StatRequest\"\035\n" +
      "\013StatRequest\022\016\n\006blobId\030\001 \002(\003\"r\n\010Response" +
      "\022,\n\014statResponse\030\002 \001(\0132\026.doss.net.StatRe" +
      "sponse\0228\n\022noSuchBlobResponse\030\020 \001(\0132\034.dos" +
      "s.net.NoSuchBlobResponse\",\n\014StatResponse" +
      "\022\016\n\006blobId\030\001 \002(\003\022\014\n\004size\030\002 \002(\003\"$\n\022NoSuch" +
      "BlobResponse\022\016\n\006blobId\030\001 \002(\003B\016B\014DossProt" +
      "ocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_doss_net_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_doss_net_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doss_net_Request_descriptor,
              new java.lang.String[] { "StatRequest", },
              doss.net.DossProtocol.Request.class,
              doss.net.DossProtocol.Request.Builder.class);
          internal_static_doss_net_StatRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_doss_net_StatRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doss_net_StatRequest_descriptor,
              new java.lang.String[] { "BlobId", },
              doss.net.DossProtocol.StatRequest.class,
              doss.net.DossProtocol.StatRequest.Builder.class);
          internal_static_doss_net_Response_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_doss_net_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doss_net_Response_descriptor,
              new java.lang.String[] { "StatResponse", "NoSuchBlobResponse", },
              doss.net.DossProtocol.Response.class,
              doss.net.DossProtocol.Response.Builder.class);
          internal_static_doss_net_StatResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_doss_net_StatResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doss_net_StatResponse_descriptor,
              new java.lang.String[] { "BlobId", "Size", },
              doss.net.DossProtocol.StatResponse.class,
              doss.net.DossProtocol.StatResponse.Builder.class);
          internal_static_doss_net_NoSuchBlobResponse_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_doss_net_NoSuchBlobResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_doss_net_NoSuchBlobResponse_descriptor,
              new java.lang.String[] { "BlobId", },
              doss.net.DossProtocol.NoSuchBlobResponse.class,
              doss.net.DossProtocol.NoSuchBlobResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
